#!/bin/bash

if [[ $(($# < 1)) != 0 ]]; then echo " \
Builds specified service \
 \
Usage: $0 <s3 bucket name to deploy lambda sources> \
" && exit; fi

DIR_SOURCE="src/lambda"
DIR_BUILD="build"
DIR_LIB="venv/lib/python3.7/site-packages"

timestamp(){
 date +"%Y-%m-%dT%T"
}

if [[ -d "$DIR_BUILD" ]]; then
  rm -rf ./${DIR_BUILD}
fi

echo $(timestamp) Creates $DIR_BUILD

echo $(timestamp) Copies $DIR_SOURCE content to $DIR_BUILD
cp -a ./${DIR_SOURCE}/. ./${DIR_BUILD}/

echo $(timestamp) Copies $DIR_LIB content to $DIR_BUILD
cp -a ./${DIR_LIB}/. ./${DIR_BUILD}/

echo $(timestamp) Packages sources...
aws cloudformation package  \
    --template-file CloudFormation.yml \
    --s3-bucket ${1} \
    --output-template-file Packaged.yml

